In [1]:
import nltk

In [2]:
para ='''Greeting everyone. Today, I am here to deliver a speech on APJ Abdul Kalam.
Dr APJ Abdul Kalam’s full name was Avul Pakir Zainuldeben Abdul Kalam, 
very few people know him by his full name as he was mostly addressed as ‘Missile Man of India’ 
and ‘People’s President’. He was born into a very poor family in Rameswaram on October 15, 1931. 
Since childhood, he enjoyed flying, and was equally curious to know how birds fly in the air?
He was very intelligent and enjoyed reading, but his family did not have sufficient income for
his school fees, so to support his education, he would wake up early in the morning and ride a
bicycle 3 kilometres from home to collect newspapers and sell them. 
He was admitted to St. Joseph's College, Tiruchirapalli, and later he went on to complete a degree
in physics in 1954 and then studied at the Madras Institute of Technology and graduated in aeronautical 
engineering in 1955. Since his childhood, Dr Abdul Alam wanted to be a pilot but couldn’t make his dream
come true. He learned from his mistakes and accomplished numerous achievements in his life. After completing
his degree, Abdul Kalam entered the Defense Department of India. He has been one of the key figures in building
the nuclear capabilities of India.
APJ Abdul Kalam was appointed to the Indian Ministry of Defense as a Technical Advisor in 1992, after which he 
served with DRDO and ISRO, the country's largest organization. Considered a national hero for successful nuclear
tests in 1998, a second successful nuclear test was conducted in Pokhran the same year under his supervision, 
after which India was included in the list of nuclear-powered nations. Abdul Kalam has been active in all space
programs and development programs in India as a scientist. For developing India's Agni missile, Kalam was called
'Missile Man.'Abdul Kalam made a special technological and scientific contribution, for which, along with Bharat
Ratna, India's highest honour, he was awarded the Padma Bhushan, Padam Vibhushan, etc. He was also awarded an honorary doctorate by more than 30 universities in the world for the same. 
In 2002, he was elected President of India and was the country's first scientist and non-political president. 
He visited many countries during his tenure as President and led India's youth through his lectures and encouraged
them to move forward.  ‘My vision for India’ was a Famous Speech of APJ Abdul Kalam delivered at IIT Hyderabad in 2011,
and is to this day my favourite speech. His far-reaching thinking gave India's growth a fresh path and became the youth's 
inspiration. Dr Abdul Kalam died on July 27, 2015, from an apparent cardiac arrest while delivering a lecture 
at IIM Shillong at the age of 83. He spent his entire life in service and inspiration for the nation and the youth, 
and his death is also while addressing the youth. His death is a never-ending loss to the country.

'''

In [3]:
sentences = nltk.sent_tokenize(para)
sentences

['Greeting everyone.',
 'Today, I am here to deliver a speech on APJ Abdul Kalam.',
 'Dr APJ Abdul Kalam’s full name was Avul Pakir Zainuldeben Abdul Kalam, \nvery few people know him by his full name as he was mostly addressed as ‘Missile Man of India’ \nand ‘People’s President’.',
 'He was born into a very poor family in Rameswaram on October 15, 1931.',
 'Since childhood, he enjoyed flying, and was equally curious to know how birds fly in the air?',
 'He was very intelligent and enjoyed reading, but his family did not have sufficient income for\nhis school fees, so to support his education, he would wake up early in the morning and ride a\nbicycle 3 kilometres from home to collect newspapers and sell them.',
 "He was admitted to St. Joseph's College, Tiruchirapalli, and later he went on to complete a degree\nin physics in 1954 and then studied at the Madras Institute of Technology and graduated in aeronautical \nengineering in 1955.",
 'Since his childhood, Dr Abdul Alam wanted to be a pilot but couldn’t make his dream\ncome true.',
 'He learned from his mistakes and accomplished numerous achievements in his life.',
 'After completing\nhis degree, Abdul Kalam entered the Defense Department of India.',
 'He has been one of the key figures in building\nthe nuclear capabilities of India.',
 "APJ Abdul Kalam was appointed to the Indian Ministry of Defense as a Technical Advisor in 1992, after which he \nserved with DRDO and ISRO, the country's largest organization.",
 'Considered a national hero for successful nuclear\ntests in 1998, a second successful nuclear test was conducted in Pokhran the same year under his supervision, \nafter which India was included in the list of nuclear-powered nations.',
 'Abdul Kalam has been active in all space\nprograms and development programs in India as a scientist.',
 "For developing India's Agni missile, Kalam was called\n'Missile Man.",
 "'Abdul Kalam made a special technological and scientific contribution, for which, along with Bharat\nRatna, India's highest honour, he was awarded the Padma Bhushan, Padam Vibhushan, etc.",
 'He was also awarded an honorary doctorate by more than 30 universities in the world for the same.',
 "In 2002, he was elected President of India and was the country's first scientist and non-political president.",
 "He visited many countries during his tenure as President and led India's youth through his lectures and encouraged\nthem to move forward.",
 '‘My vision for India’ was a Famous Speech of APJ Abdul Kalam delivered at IIT Hyderabad in 2011,\nand is to this day my favourite speech.',
 "His far-reaching thinking gave India's growth a fresh path and became the youth's \ninspiration.",
 'Dr Abdul Kalam died on July 27, 2015, from an apparent cardiac arrest while delivering a lecture \nat IIM Shillong at the age of 83.',
 'He spent his entire life in service and inspiration for the nation and the youth, \nand his death is also while addressing the youth.',
 'His death is a never-ending loss to the country.']

In [4]:
len(sentences)

24

In [5]:
words = nltk.word_tokenize(para)

In [6]:
words[:10]

['Greeting', 'everyone', '.', 'Today', ',', 'I', 'am', 'here', 'to', 'deliver']

In [7]:
len(words)

565

**Stemming**

In [8]:
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [9]:
stemmer = PorterStemmer()

In [10]:

for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])
    words = [stemmer.stem(word) for word in words if word not in set(stopwords.words("english"))]
    sentences[i]=" ".join(words)

In [11]:
sentences

['greet everyon .',
 'today , i deliv speech apj abdul kalam .',
 'dr apj abdul kalam ’ full name avul pakir zainuldeben abdul kalam , peopl know full name mostli address ‘ missil man india ’ ‘ peopl ’ presid ’ .',
 'he born poor famili rameswaram octob 15 , 1931 .',
 'sinc childhood , enjoy fli , equal curiou know bird fli air ?',
 'he intellig enjoy read , famili suffici incom school fee , support educ , would wake earli morn ride bicycl 3 kilometr home collect newspap sell .',
 "he admit st. joseph 's colleg , tiruchirap , later went complet degre physic 1954 studi madra institut technolog graduat aeronaut engin 1955 .",
 'sinc childhood , dr abdul alam want pilot ’ make dream come true .',
 'he learn mistak accomplish numer achiev life .',
 'after complet degre , abdul kalam enter defens depart india .',
 'he one key figur build nuclear capabl india .',
 "apj abdul kalam appoint indian ministri defens technic advisor 1992 , serv drdo isro , countri 's largest organ .",
 'consid nation hero success nuclear test 1998 , second success nuclear test conduct pokhran year supervis , india includ list nuclear-pow nation .',
 'abdul kalam activ space program develop program india scientist .',
 "for develop india 's agni missil , kalam call 'missil man .",
 "'abdul kalam made special technolog scientif contribut , , along bharat ratna , india 's highest honour , award padma bhushan , padam vibhushan , etc .",
 'he also award honorari doctor 30 univers world .',
 "in 2002 , elect presid india countri 's first scientist non-polit presid .",
 "he visit mani countri tenur presid led india 's youth lectur encourag move forward .",
 '‘ my vision india ’ famou speech apj abdul kalam deliv iit hyderabad 2011 , day favourit speech .',
 "hi far-reach think gave india 's growth fresh path becam youth 's inspir .",
 'dr abdul kalam die juli 27 , 2015 , appar cardiac arrest deliv lectur iim shillong age 83 .',
 'he spent entir life servic inspir nation youth , death also address youth .',
 'hi death never-end loss countri .']

**Stemming change some word into not meaningful word so Lemmatizer is introduce**

 **Lemmatizer**

In [12]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [13]:
sentences2 = nltk.sent_tokenize(para)

In [14]:
for i in range(len(sentences2)):
    words = nltk.word_tokenize(sentences2[i])
    words = [lemmatizer.lemmatize(word) for word in words if word not in set(stopwords.words("english"))]
    sentences2[i]=" ".join(words)

In [15]:
sentences2

['Greeting everyone .',
 'Today , I deliver speech APJ Abdul Kalam .',
 'Dr APJ Abdul Kalam ’ full name Avul Pakir Zainuldeben Abdul Kalam , people know full name mostly addressed ‘ Missile Man India ’ ‘ People ’ President ’ .',
 'He born poor family Rameswaram October 15 , 1931 .',
 'Since childhood , enjoyed flying , equally curious know bird fly air ?',
 'He intelligent enjoyed reading , family sufficient income school fee , support education , would wake early morning ride bicycle 3 kilometre home collect newspaper sell .',
 "He admitted St. Joseph 's College , Tiruchirapalli , later went complete degree physic 1954 studied Madras Institute Technology graduated aeronautical engineering 1955 .",
 'Since childhood , Dr Abdul Alam wanted pilot ’ make dream come true .',
 'He learned mistake accomplished numerous achievement life .',
 'After completing degree , Abdul Kalam entered Defense Department India .',
 'He one key figure building nuclear capability India .',
 "APJ Abdul Kalam appointed Indian Ministry Defense Technical Advisor 1992 , served DRDO ISRO , country 's largest organization .",
 'Considered national hero successful nuclear test 1998 , second successful nuclear test conducted Pokhran year supervision , India included list nuclear-powered nation .',
 'Abdul Kalam active space program development program India scientist .',
 "For developing India 's Agni missile , Kalam called 'Missile Man .",
 "'Abdul Kalam made special technological scientific contribution , , along Bharat Ratna , India 's highest honour , awarded Padma Bhushan , Padam Vibhushan , etc .",
 'He also awarded honorary doctorate 30 university world .',
 "In 2002 , elected President India country 's first scientist non-political president .",
 "He visited many country tenure President led India 's youth lecture encouraged move forward .",
 '‘ My vision India ’ Famous Speech APJ Abdul Kalam delivered IIT Hyderabad 2011 , day favourite speech .',
 "His far-reaching thinking gave India 's growth fresh path became youth 's inspiration .",
 'Dr Abdul Kalam died July 27 , 2015 , apparent cardiac arrest delivering lecture IIM Shillong age 83 .',
 'He spent entire life service inspiration nation youth , death also addressing youth .',
 'His death never-ending loss country .']

In [16]:
import pandas as pd

In [17]:
pd.DataFrame(sentences2)

                                                    0
0                                 Greeting everyone .
1          Today , I deliver speech APJ Abdul Kalam .
2   Dr APJ Abdul Kalam ’ full name Avul Pakir Zain...
3   He born poor family Rameswaram October 15 , 19...
4   Since childhood , enjoyed flying , equally cur...
5   He intelligent enjoyed reading , family suffic...
6   He admitted St. Joseph 's College , Tiruchirap...
7   Since childhood , Dr Abdul Alam wanted pilot ’...
8   He learned mistake accomplished numerous achie...
9   After completing degree , Abdul Kalam entered ...
10  He one key figure building nuclear capability ...
11  APJ Abdul Kalam appointed Indian Ministry Defe...
12  Considered national hero successful nuclear te...
13  Abdul Kalam active space program development p...
14  For developing India 's Agni missile , Kalam c...
15  'Abdul Kalam made special technological scient...
16  He also awarded honorary doctorate 30 universi...
17  In 2002 , elected President India country 's f...
18  He visited many country tenure President led I...
19  ‘ My vision India ’ Famous Speech APJ Abdul Ka...
20  His far-reaching thinking gave India 's growth...
21  Dr Abdul Kalam died July 27 , 2015 , apparent ...
22  He spent entire life service inspiration natio...
23              His death never-ending loss country .

In [18]:
pd.DataFrame(sentences)

                                                    0
0                                     greet everyon .
1            today , i deliv speech apj abdul kalam .
2   dr apj abdul kalam ’ full name avul pakir zain...
3    he born poor famili rameswaram octob 15 , 1931 .
4   sinc childhood , enjoy fli , equal curiou know...
5   he intellig enjoy read , famili suffici incom ...
6   he admit st. joseph 's colleg , tiruchirap , l...
7   sinc childhood , dr abdul alam want pilot ’ ma...
8      he learn mistak accomplish numer achiev life .
9   after complet degre , abdul kalam enter defens...
10      he one key figur build nuclear capabl india .
11  apj abdul kalam appoint indian ministri defens...
12  consid nation hero success nuclear test 1998 ,...
13  abdul kalam activ space program develop progra...
14  for develop india 's agni missil , kalam call ...
15  'abdul kalam made special technolog scientif c...
16   he also award honorari doctor 30 univers world .
17  in 2002 , elect presid india countri 's first ...
18  he visit mani countri tenur presid led india '...
19  ‘ my vision india ’ famou speech apj abdul kal...
20  hi far-reach think gave india 's growth fresh ...
21  dr abdul kalam die juli 27 , 2015 , appar card...
22  he spent entir life servic inspir nation youth...
23                  hi death never-end loss countri .

**Bag of words**

In [19]:
from sklearn.feature_extraction.text import CountVectorizer
cv =CountVectorizer(max_features=1500)

In [20]:
X = cv.fit_transform(sentences2)

In [21]:
pd.DataFrame(X.toarray(),columns=cv.get_feature_names())

C:\Users\RAHUL SUTHAR\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,15,1931,1954,1955,1992,1998,2002,2011,2015,27,...,vision,visited,wake,wanted,went,world,would,year,youth,zainuldeben
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
6,0,0,1,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
17,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
19,0,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
21,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
cv2 =CountVectorizer(max_features=1500)
X2=cv2.fit_transform(sentences)
pd.DataFrame(X2.toarray(),columns=cv2.get_feature_names())

C:\Users\RAHUL SUTHAR\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,15,1931,1954,1955,1992,1998,2002,2011,2015,27,...,vision,visit,wake,want,went,world,would,year,youth,zainuldeben
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
6,0,0,1,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
17,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
19,0,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
21,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# TF-IDF

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer

tiv = TfidfVectorizer()

In [26]:
tf_idf=tiv.fit_transform(sentences2)

In [27]:
pd.DataFrame(tf_idf.toarray(),columns=tiv.get_feature_names())

C:\Users\RAHUL SUTHAR\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,15,1931,1954,1955,1992,1998,2002,2011,2015,27,...,vision,visited,wake,wanted,went,world,would,year,youth,zainuldeben
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.205008
3,0.374976,0.374976,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.218764,0.000000,0.000000,0.000000,0.218764,0.000000,0.000000,0.000000
6,0.000000,0.000000,0.228742,0.228742,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.228742,0.000000,0.000000,0.000000,0.000000,0.000000
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.324318,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,0.000000,0.000000,0.000000,0.000000,0.272473,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,0.000000,0.000000,0.000000,0.000000,0.000000,0.188733,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.188733,0.000000,0.000000
13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.380825,0.000000,0.000000,0.000000,0.000000
17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.31381,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.313226,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.251647,0.000000
19,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.272031,0.000000,0.000000,...,0.272031,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.248483,0.000000
21,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.267075,0.267075,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.488332,0.000000
23,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000